# -*- coding: utf-8 -*-
"""KS first class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Og6mMrefkXyAm1FwM35PrCYqbXsWYqr
"""

promm=np.array([[1,2,3,4],[5,6,7,8]])
print(promm.shape)
prompt=np.array([[[1,2,3,4],[6,7,8,9]],
                 [[1,2,3,4],[6,7,8,9]],
                  [[1,2,3,4],[6,7,8,9]]])
print(prompt.shape)
print(promm.ndim)
print(prompt.ndim)

cars=[["toyata", "ferrari", "tesla"], ["toyata", "ferrari", "tesla"]]

cars

cars[0][1]

Alpha=np.array([1,2,3,4,5,6,7,8,9,10])
print(Alpha[0])

arr=np.array([1,2,3,4])
print(arr[2])
arr=np.array([2,4,5,7,0])
print(arr[4])
Alpha=np.array([[1,3,4,5],[3,45,2,4]])
print(Alpha[0][3])

Beta=np.array([[3,4,52,4],[4,3,2,1]])
print(Beta[1][3])

Sigma=np.array([[[1,2,3,4,4],[3,4,2,4,9]]])
print(Sigma[0][1][2])

np.array([[[[1,2,3,4],[6,7,8,9]],
                 [[1,2,3,4],[6,7,8,9]],
                  [[1,2,3,4],[6,7,8,9]]],
[[[1,2,3,4],[6,7,8,9]],
                 [[1,2,3,4],[6,7,8,9]],
                  [[1,2,3,4],[6,7,8,9]]]])

